#!/usr/bin/env python3
"""DDP 한방에 — CNN_DDP → Contrastive_DDP sequential 실행.

사용:
    CUDA_VISIBLE_DEVICES=0,1,2,3 python scripts/train_pipeline_ddp.py
        → 4 GPU 으로 CNN 학습 → backbone 으로 Contrastive 학습

내부적으로 subprocess.run 으로 두 스크립트 순차 실행 (각자 mp.spawn 사용).
"""
# ===================================================================
# === CONFIG ===
# ===================================================================
CNN_DATA_DIR          = "E:/data/images/cnn_train"
CL_TRAIN_DIR          = "E:/data/images/contrastive_train"
CL_EVAL_DIR           = "E:/data/images/contrastive_eval"

# 두 stage 의 hyperparam 은 각 _ddp.py 의 CONFIG block 을 직접 수정
#   scripts/train_cnn_ddp.py        ← CNN
#   scripts/train_contrastive_ddp.py ← Contrastive
#
# 이 pipeline 은 CNN best_model.pth path 를 자동 추출 후 Contrastive 에 inject
PIPELINE_TAG          = "pipeline_ddp"
# ===================================================================

from __future__ import annotations

import json
import os
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path


def main():
    repo = Path(__file__).parent.parent.resolve()
    ts = datetime.now().strftime("%y%m%d_%H%M%S")
    run_dir = repo / "runs" / f"{ts}_{PIPELINE_TAG}"
    run_dir.mkdir(parents=True, exist_ok=True)
    log = run_dir / "pipeline.log"
    print(f"[pipeline_ddp] {run_dir}")
    with open(log, "w", encoding="utf-8") as f:
        f.write(f"[pipeline_ddp] {datetime.now().isoformat()}\n")
        f.write(f"CUDA_VISIBLE_DEVICES={os.environ.get('CUDA_VISIBLE_DEVICES','(unset)')}\n\n")

    env = {**os.environ, "PYTHONUNBUFFERED": "1"}

    # ============ Stage 1: CNN DDP ============
    print("\n" + "=" * 60)
    print("STAGE 1 — CNN DDP")
    print("=" * 60)
    t0 = time.time()
    rc = subprocess.run(
        [sys.executable, "-u", str(repo / "scripts" / "train_cnn_ddp.py")],
        env=env, cwd=str(repo),
    ).returncode
    print(f"[stage1 done] rc={rc}, elapsed={(time.time()-t0)/60:.1f} min")
    if rc != 0:
        raise SystemExit(f"CNN DDP failed rc={rc}")

    # latest CNN run dir from runs/
    cnn_runs = sorted((repo / "runs").glob("*_cnn_ddp"),
                      key=lambda p: p.stat().st_mtime, reverse=True)
    if not cnn_runs:
        raise SystemExit("no *_cnn_ddp run dir found after CNN stage")
    cnn_run = cnn_runs[0]
    cnn_best = cnn_run / "cnn" / "best_model.pth"
    print(f"[stage1 result] {cnn_run}  best={cnn_best.exists()}")
    if not cnn_best.exists():
        raise SystemExit(f"no best_model.pth in {cnn_run}")

    # ============ Stage 2: Contrastive DDP ============
    print("\n" + "=" * 60)
    print("STAGE 2 — Contrastive DDP")
    print("=" * 60)
    # inject CNN backbone path via env
    env["BACKBONE_CKPT_OVERRIDE"] = str(cnn_best)

    # train_contrastive_ddp.py 의 BACKBONE_CKPT 를 환경변수로 override 하기 위해
    # 임시 wrapper 작성 (script 내부 BACKBONE_CKPT 변수 변경)
    wrapper = run_dir / "_run_contrastive_ddp.py"
    wrapper.write_text(f"""
# Auto-generated by train_pipeline_ddp.py
import sys, runpy
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "scripts"))
import train_contrastive_ddp as m
m.BACKBONE_CKPT = r'''{cnn_best}'''
m.OUTPUT_ROOT = str(Path(__file__).parent.parent.parent / "runs")
m.TAG = "contrastive_ddp_pipe"
m.launch_ddp(m.train_worker)
""", encoding="utf-8")

    t0 = time.time()
    rc = subprocess.run(
        [sys.executable, "-u", str(wrapper)],
        env=env, cwd=str(repo),
    ).returncode
    print(f"[stage2 done] rc={rc}, elapsed={(time.time()-t0)/60:.1f} min")
    if rc != 0:
        raise SystemExit(f"Contrastive DDP failed rc={rc}")

    cl_runs = sorted((repo / "runs").glob("*_contrastive_ddp_pipe"),
                     key=lambda p: p.stat().st_mtime, reverse=True)
    if cl_runs:
        cl_run = cl_runs[0]
        print(f"[stage2 result] {cl_run}")

    # ============ Pipeline summary ============
    summary = {
        "pipeline_run": str(run_dir),
        "cnn_run": str(cnn_run),
        "cnn_best": str(cnn_best),
        "contrastive_run": str(cl_run) if cl_runs else None,
        "contrastive_best": str(cl_run / "contrastive" / "best_model.pt") if cl_runs else None,
        "cuda_visible": os.environ.get("CUDA_VISIBLE_DEVICES", "(unset)"),
        "finished_at": datetime.now().isoformat(),
    }
    (run_dir / "summary.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n[OUT] {run_dir}")
    print(f"  CNN best:         {cnn_best}")
    if cl_runs:
        print(f"  Contrastive best: {cl_run / 'contrastive' / 'best_model.pt'}")


if __name__ == "__main__":
    main()
